---
# tasks file for bloodhound
- name: Create directory for BloodHound
  file:
    path: "/tools/BloodHound"
    state: directory

# We will install a BloodHound release, but we go ahead and install
# the bloodhound package here so we get all dependencies
- name: Install the bloodhound package
  apt:
    name: bloodhound

- name: Download and untar the BloodHound tarball
  unarchive:
    src: "https://github.com/BloodHoundAD/BloodHound/tarball/master"
    dest: /tools/BloodHound
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: Install the unzip package
  package:
    name: unzip

- name: Download and unzip the BloodHound release
  unarchive:
    src: "https://github.com/BloodHoundAD/BloodHound/releases/download/2.2.1\
    /BloodHound-linux-x64.zip"
    dest: /tools/BloodHound
    remote_src: yes
