---
# tasks file for bloodhound
- name: Install bloodhound via apt module
  apt:
    name: 'bloodhound'

- name: Create directory for each tool
  file:
    path: "/tools/BloodHound"
    state: directory

- name: download Bloodhound source as backup
  unarchive:
    src: "https://github.com/BloodHoundAD/BloodHound/archive/2.2.1.tar.gz"
    dest: /tools/BloodHound
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: set initial neo4j password used by bloodhound
  command: /usr/share/neo4j/bin/neo4j-admin set-initial-password "{{ bloodhound_password }}"
